---
- hosts: localhost
  connection: local
  gather_facts: False
  any_errors_fatal: True
  roles:
    - aws_instance

- name: Setup DB Servers
  hosts: db_servers
  any_errors_fatal: True
  roles:
    - python
    - mysql_db

- name: Setup Web Servers
  hosts: web_servers
  any_errors_fatal: True
  roles:
    - python
    - flask_web

