---
- name: Install db packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server 
    - mysql-client

- name: Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create Database User 
  shell: sud mysql -uroot -p12345678 -e"CREATE USER {{ db_user }}@.* identified by {{ db_user_password }} ";
  ignore_errors: yes

- name: Set Privileges To Database User 
  shell: sudo mysql -uroot -p12345678 -e"GRANT ALL PRIVILEGES on {{ db_name }}.* to {{ db_user }}";
  ignore_errors: yes

- name: Create Application Database
  shell: sudo mysql -uroot -p12345678 -e"CREATE DATABASE {{ db_name }}";
  ignore_errors: yes
  

