---
- name: Install db packages
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server 
    - mysql-client

- name: Start Mysql Service
  service:
    name: mysql
    state: started
    enabled: yes

- name: Example using login_unix_socket to connect to server
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_user_password}}"
    priv: '*.*:ALL,GRANT'
    login_unix_socket: /var/run/mysqld/mysqld.sock
    state: present

- name: Create a new database
  mysql_db:
    name: "{{ db_name }}"
    state: present
  

