---
- name: Install Flask dependencies
  pip: 
    name: "{{ item }}"
    state: present
    executable: pip3
  with_items:
    - flask
    - flask-mysql

- name: Download app from git
  git: 
    repo: 'https://github.com/mmpriebe/flask_app.git'
    dest: /opt/app

- name: Start Web Server
  shell: "nohup flask run --host=0.0.0.0 --port=80 &"
  environment:
    FLASK_APP: /opt/app/app.py  

