---
- name: Create ec2 Instances
  ec2:
    key_name: "{{ ec2_keypair }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    group: "{{ ec2_security_group }}"
    wait: yes
    count: 2
    region: "{{ ec2_region }}"
    instance_tags:
      Name: "{{ ec2_tag_Name }}"
      Env: "{{ ec2_tag_env }}"
   